apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: atlantis
resources:
  - namespace.yaml
  - repo-config.yaml
  - secret.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
